export enum JOB_NAMES {
  LOCAL_SCOPED_JOB_FOR_QUEUE1 = 'local-scoped-job-for-queue1',
  LOCAL_SCOPED_JOB_FOR_QUEUE2 = 'local-scoped-job-for-queue2',
  LOCAL_SCOPED_JOB_FOR_QUEUE3 = 'local-scoped-job-for-queue3',
  LOCAL_SCOPED_JOB_FOR_QUEUE4 = 'local-scoped-job-for-queue4',
  LOCAL_SCOPED_JOB_FOR_QUEUE5 = 'local-scoped-job-for-queue5',
  LOCAL_SCOPED_JOB_FOR_QUEUE6 = 'local-scoped-job-for-queue6',
  LOCAL_SCOPED_JOB_FOR_QUEUE7 = 'local-scoped-job-for-queue7',
  LOCAL_SCOPED_JOB_FOR_QUEUE8 = 'local-scoped-job-for-queue8',
  LOCAL_SCOPED_JOB_FOR_QUEUE9 = 'local-scoped-job-for-queue9',
  LOCAL_SCOPED_JOB_FOR_QUEUE10 = 'local-scoped-job-for-queue10',
  GLOBAL_SCOPED_JOB_FOR_QUEUE1 = 'global-scoped-job-for-queue1',
  GLOBAL_SCOPED_JOB_FOR_QUEUE2 = 'global-scoped-job-for-queue2',
  GLOBAL_SCOPED_JOB_FOR_QUEUE3 = 'global-scoped-job-for-queue3',
  GLOBAL_SCOPED_JOB_FOR_QUEUE4 = 'global-scoped-job-for-queue4',
  GLOBAL_SCOPED_JOB_FOR_QUEUE5 = 'global-scoped-job-for-queue5',
  GLOBAL_SCOPED_JOB_FOR_QUEUE6 = 'global-scoped-job-for-queue6',
  GLOBAL_SCOPED_JOB_FOR_QUEUE7 = 'global-scoped-job-for-queue7',
  GLOBAL_SCOPED_JOB_FOR_QUEUE8 = 'global-scoped-job-for-queue8',
  GLOBAL_SCOPED_JOB_FOR_QUEUE9 = 'global-scoped-job-for-queue9',
  GLOBAL_SCOPED_JOB_FOR_QUEUE10 = 'global-scoped-job-for-queue10',
}
